[workspace]

members = [".", "macro"]
default-members = ["."]

[package]
name = "pollster"
version = "0.4.0"
description = "Synchronously block the thread until a future completes"
categories = ["asynchronous", "concurrency"]
keywords = ["async", "minimal", "executor", "runtime", "block_on"]
repository = "https://github.com/zesterer/pollster"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"

[features]
macro = ["pollster-macro"]

[dependencies]
pollster-macro = { version = "0.4.0", path = "macro", optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
parking_lot = { version = "0.12.3", default-features = false }

# [target.'cfg(target_family = "wasm")'.dependencies]
# web-sys = { version = "0.3", default-features = false }
# js-sys = { version = "0.3", default-features = false }

[dev-dependencies]
futures-timer = "3.0"
tokio = { version = "1", features = ["sync"] }

[package.metadata.docs.rs]
all-features = true
targets = []
rustdoc-args = ["--cfg", "docsrs"]
